### ISSUE TITLE
TODO：待解决的问题

### ISSUE THREAD

**Issue by ccssu** [Oneflow-Inc/one-yolov5#115]
- [ ] 模型导出精度不够  [注意 ：使用[GPU能够成功导出onnx模型](https://github.com/Oneflow-Inc/one-yolov5/issues/115#issuecomment-1447911779)  ， 但是 使用 cpu导出精度不够 ] https://github.com/Oneflow-Inc/one-yolov5/issues/112
- [ ] 分类训练精度达标 https://github.com/Oneflow-Inc/one-yolov5/pull/111#issuecomment-1442657257
- [ ] <details open><summary> 分类训练性能差 </summary> ![image](https://user-images.githubusercontent.com/109639975/221357599-f4dd48f0-42ac-4a8a-ab9e-348b390dd65b.png)

</details>

**Comment by ccssu** [comment]
## 版本 信息 
- oneflow.__version__= '0.9.1.dev20230226+cu117'
- 机器 a100 


## 使用GPU导出模型成功没有报错 
启动指令  `python export.py --weights /home/fengwen/one-yolov5/test_export/exp/weights/last.of --include onnx --device 0` 

主要修改如下图 ，添加 `mtype` 判断 {True Segment , False: Detect}
![image](https://user-images.githubusercontent.com/109639975/221823253-576b2bdb-0cb4-4271-b602-5b35dd38d613.png)

**Comment by BBuf** [comment]
> ## 版本 信息
> 
>     * oneflow.**version**= '0.9.1.dev20230226+cu117'
> 
>     * 机器 a100
> 
> 
> ## 使用GPU导出模型成功没有报错
> 
> 启动指令 `python export.py --weights /home/fengwen/one-yolov5/test_export/exp/weights/last.of --include onnx --device 0`
> 
> 主要修改如下图 ，添加 `mtype` 判断 {True Segment , False: Detect} ![image](https://user-images.githubusercontent.com/109639975/221823253-576b2bdb-0cb4-4271-b602-5b35dd38d613.png)

这个地方我有点疑问，在main分支的one-yolov5 检测模型导出的时候是直接把网络结构中最后那个 Detect 层删掉不导出的，为什么这里要导出Detect层的内容呢？https://github.com/Oneflow-Inc/one-yolov5/blob/main/export.py#L500 & https://github.com/Oneflow-Inc/one-yolov5/blob/main/models/yolo.py#L89
